version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm ci
  build:
    commands:
      - echo "Running build"
      - npm run build
artifacts:
  # Upload only the built assets
  base-directory: dist
  files:
    - '**/*'
  discard-paths: no
