version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
  build:
    commands:
      - echo Build started on 'date'
      - echo compiling the application
artifacts:
  files:
    - '**/*'
  base-directory: build
