version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Copying files..."
artifacts:
  files:
    - '**/*'
  base-directory: .
