version: 0.2

phases:
  install:
    commands:
      - echo Installing...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the application...
      # If using React/Vue/Angular, run build commands here
      # For plain HTML, no build step needed
artifacts:
  files:
    - '**/*'
  base-directory: s3-site-build   # 👈 VERY IMPORTANT: should point to folder where index.html exists
